// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFaH9IRdo2X9_jqB4Vx6bZbNRXWH94w4',
    appId: '1:1061909410033:web:8a2d0db730c2ca64f83950',
    messagingSenderId: '1061909410033',
    projectId: 'instagram-aa7aa',
    authDomain: 'instagram-aa7aa.firebaseapp.com',
    storageBucket: 'instagram-aa7aa.firebasestorage.app',
    measurementId: 'G-79V1CB01QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0LAbdfx1ljlOTr06PE6EsBmiyfb9jnI',
    appId: '1:1061909410033:android:711d2df495b99665f83950',
    messagingSenderId: '1061909410033',
    projectId: 'instagram-aa7aa',
    storageBucket: 'instagram-aa7aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhcadrlKpFkyV5wFRt1AvIYwnYK4IzSAI',
    appId: '1:1061909410033:ios:1acbeaaeae754d7df83950',
    messagingSenderId: '1061909410033',
    projectId: 'instagram-aa7aa',
    storageBucket: 'instagram-aa7aa.firebasestorage.app',
    iosBundleId: 'com.imayubalam.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhcadrlKpFkyV5wFRt1AvIYwnYK4IzSAI',
    appId: '1:1061909410033:ios:1acbeaaeae754d7df83950',
    messagingSenderId: '1061909410033',
    projectId: 'instagram-aa7aa',
    storageBucket: 'instagram-aa7aa.firebasestorage.app',
    iosBundleId: 'com.imayubalam.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFaH9IRdo2X9_jqB4Vx6bZbNRXWH94w4',
    appId: '1:1061909410033:web:a783ee799cabcdd0f83950',
    messagingSenderId: '1061909410033',
    projectId: 'instagram-aa7aa',
    authDomain: 'instagram-aa7aa.firebaseapp.com',
    storageBucket: 'instagram-aa7aa.firebasestorage.app',
    measurementId: 'G-J1DEB6SB2Y',
  );
}
